channels:
    - conda-forge
dependencies:
    - r-base=3.6
    - r-rcpp
    - r-ape
    - r-cairo
    - r-clue
    - r-cluster
    - r-cowplot
    - r-cvtools
    - r-dendextend
    - r-downloader
    - r-e1071
    - r-factoextra
    - r-geometry
    - r-ggraph
    - r-gridextra
    - r-igraph
    - r-jpeg
    - r-keras
    - r-lattice
    - r-lavaan
    - r-lme4
    - r-magick
    - r-magrittr
    - r-mass
    - r-mclust
    - r-nbclust
    - r-openimager
    - r-ordinal
    - r-orthopolynom
    - r-plyr
    - r-png
    - r-progress
    - r-raster
    - r-rcolorbrewer
    - r-readbitmap
    - r-readxl
    - r-rgeos
    - r-rsolnp
    - r-scales
    - r-sem
    - r-semtools
    - r-sp
    - r-spatstat
    - r-tidygraph
    - r-tidyverse
    - r-vegan
    - r-vsurf
    - r-xml
